
var distance=function(x1,y1,x2,y2){return Math.sqrt(Math.abs(Math.pow(x1-x2,2))+Math.abs(Math.pow(y1-y2,2)));};var Planet=function(opt){opt=opt||{};this._id=opt._id||'home';this._x=opt._x||0;this._y=opt._y||0;this._size=opt._size||60;this._starPort=opt._starPort===undefined?true:opt._starPort;this._ore=opt._ore||10;this._oreMax=10;this._oreRate=3000;this._lastUpdate=new Date();};Planet.prototype.SPCost=function(){var d=Math.floor(distance(0,0,this._x,this._y));return d;};var World=(function(){var status={vpw:640,vph:480,money:1000,d:0,planets:[],selectedPlanet:{},onPlanet:function(){var i=this.planets.length,p,d;while(i--){p=this.planets[i];if(distance(this.vpx+this.ship.x,this.vpy+this.ship.y,p._x,p._y)<=p._size){return p;}}
return false;},genRim:function(pc,d){var pl,r,p=0;pc=pc||50;d=d||1000;while(p<pc){r=Math.PI/(pc/2)*p;pl=new Planet({_id:'rim_d'+d+'_'+p,_x:Math.cos(r)*d,_y:Math.sin(r)*d,_size:30,_ore:0,_starPort:false});this.planets.push(pl);p+=1;}},genPlanets:function(){this.planets=[];this.planets.push(new Planet());this.genRim(30,1000);this.genRim(120,10000);},ship:{heading:25,speed:5,x:0,y:0,ore:0,maxOre:40,setHome:function(){status.vpx=0-status.vpw/2;status.vpy=0-status.vph/2;this.heading=25;this.speed=0;this.x=status.vpw/2;this.y=status.vph/2;},loadOre:function(oreAmount,cb){if(this.ore+oreAmount<this.maxOre){this.ore+=oreAmount;cb();}},headingChange:function(down){if(down){this.heading-=1;}else{this.heading+=1;}
if(this.heading<0){this.heading=99;}
if(this.heading>100){this.heading=0;}},speedChange:function(down){if(down){this.speed-=1;}else{this.speed+=1;}
if(this.speed>=21){this.speed=20;}
if(this.speed<=0){this.speed=0;}}},update:function(){var radian=Math.PI/50*this.ship.heading;this.d=distance(this.vpx+this.ship.x,this.vpy+this.ship.y,0,0);this.vpx+=Math.cos(radian)*this.ship.speed;this.vpy+=Math.sin(radian)*this.ship.speed;var self=this;this.planets.forEach(function(p){var d=distance(self.vpx+self.ship.x,self.vpy+self.ship.y,p._x,p._y);if(d<500){api.updatePlanet(p);}});}};var api={newGame:function(){status.genPlanets();status.ship.setHome();},buy:function(what){var p=status.selectedPlanet;switch(what){case'sp':var cost=p.SPCost();if(status.money>=cost){status.money-=cost;p._lastUpdate=new Date();p._starPort=true;}
break;}},update:status.update.bind(status),updatePlanet:function(p){p=p===undefined?status.selectedPlanet:p;var now=new Date,t=now-p._lastUpdate,deltaOre;if(p._starPort){if(t>p._oreRate){if(p._id=='home'){if(p._ore>0){p._ore-=1;status.money+=100;}}else{deltaOre=Math.floor(t/p._oreRate);if(deltaOre+p._ore>p._oreMax){p._ore=p._oreMax;}else{p._ore+=deltaOre;}}
p._lastUpdate=new Date();}}},getStatus:function(){return status;}};api.newGame();return api;}
());var Canvas=(function(){var canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=640;canvas.height=480;document.body.appendChild(canvas);var cls=function(){ctx.fillStyle='#000000';ctx.fillRect(0,0,canvas.width,canvas.height);},drawGrid=function(xRatio,yRatio){var cellSize=128,w=5,h=4,sx,sy;xRatio=xRatio||0;yRatio=yRatio||0;sx=-cellSize+cellSize*xRatio;sy=-cellSize+cellSize*yRatio;y=sy;ctx.strokeStyle='#808080';while(y<cellSize*h){x=sx;while(x<cellSize*w){ctx.strokeRect(x,y,cellSize,cellSize);x+=cellSize;}
y+=cellSize;}},drawShip=function(){var w=World.getStatus(),s=w.ship;ctx.save();ctx.translate(s.x,s.y);ctx.rotate(Math.PI/50*s.heading);ctx.strokeStyle='#00ff00';ctx.beginPath();ctx.arc(0,0,10,0,Math.PI*2);ctx.closePath();ctx.stroke();ctx.strokeStyle='#ff0000';ctx.beginPath();ctx.arc(0,0,15,Math.PI-.5,Math.PI+.5);ctx.stroke();ctx.restore();},drawPlanets=function(){var w=World.getStatus(),pl=w.planets;ctx.strokeStyle='#000000';pl.forEach(function(p){var x=w.vpx+w.vpw+-p._x,y=w.vpy+w.vph+-p._y;ctx.fillStyle=p._starPort===true?'#00cfcf':'#afafaf';ctx.beginPath();ctx.closePath();ctx.arc(x,y,p._size,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#ffffff';ctx.font='15px courier';ctx.fillText('pos: ('+Math.floor(p._x)+','+Math.floor(p._y)+')',x,y);ctx.fillText('ore: '+p._ore,x,y+15);});},drawInfo=function(){var w=World.getStatus();ctx.fillStyle='#ffffff';ctx.textBaseline='top';ctx.font='10px courier';ctx.fillText('distance: '+w.d,10,10);ctx.fillText('speed: '+w.ship.speed,10,20);ctx.fillText('money: '+w.money,10,30);ctx.fillText('ship pos : ('+Math.floor(w.vpx+w.ship.x)+','+Math.floor(w.vpy+w.ship.y)+')',10,40);ctx.fillText('ship ore: '+w.ship.ore+'/'+w.ship.maxOre,10,50);},api={draw:{start:function(){},game:function(){var w=World.getStatus();cls();drawGrid(w.vpx%w.vpw/w.vpw,w.vpy%w.vph/w.vph);drawPlanets();drawShip();drawInfo();},planetMenu:function(){var w=World.getStatus(),prop,i=0;cls();ctx.fillStyle='rgba(0,255,255,.6)';ctx.font='10px courier';ctx.fillText('planet menu: ',10,10);ctx.fillText('money: '+w.money,10,20);for(prop in w.selectedPlanet){if(prop[0]==='_'){ctx.fillText(prop+' : '+w.selectedPlanet[prop],10,50+10*i);}
i+=1;}}}};cls();return api;}
());var Main=(function(){var currentState='start',frameRate=1000/30,lastTick=new Date(0),state={start:{tick:function(){World.newGame();currentState='game';},keyboardDown:function(e){}},game:{tick:function(){World.update();},keyboardDown:function(e){var w=World.getStatus();switch(e.keyCode){case 68:w.ship.headingChange()
break;case 65:w.ship.headingChange(true);break;case 87:w.ship.speedChange();break;case 83:w.ship.speedChange(true);break;case 76:var p=w.onPlanet();if(p){w.selectedPlanet=p;currentState='planetMenu';}
break;}}},planetMenu:{tick:function(){World.updatePlanet();},keyboardDown:function(e){var w=World.getStatus(),p=w.selectedPlanet;if(e.keyCode==76){currentState='game';}
if(e.keyCode==49){if(!p._starPort){World.buy('sp');}}
if(e.keyCode==50){if(p._id==='home'){p._ore+=w.ship.ore;w.ship.ore=0;}else{w.ship.loadOre(p._ore,function(){p._ore=0;});}}}}};loop=function(){var now=new Date();requestAnimationFrame(loop);if(now-lastTick>=frameRate){state[currentState].tick();Canvas.draw[currentState]();lastTick=new Date();}};loop();window.addEventListener('keydown',function(e){state[currentState].keyboardDown(e);});return{changeState:function(state){currentState=state;}}}
());